FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build
WORKDIR /src
COPY ["HealthConnect/HealthConnect.csproj", "HealthConnect/"]
RUN dotnet restore "HealthConnect/HealthConnect.csproj"
COPY . .
WORKDIR "/src/HealthConnect"
RUN dotnet build "HealthConnect.csproj" -c Debug -o /app/build

FROM build AS publish
RUN dotnet publish "HealthConnect.csproj" -c Debug -o /app/publish

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS dev
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "watch", "run"]
