version: "3.9"

networks:
  my-network:
    driver: bridge

services:
  mysql:
    env_file:
      - .env
    build: ./database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_ROOT_HOST: '%'  # needs to be enclosed with quotes

    volumes:
      - ./database/data:/var/lib/mysql
      - ./database:/docker-entrypoint-initdb.d
    networks:
      - my-network

  backend:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    volumes:
      - ./HealthConnect/output:/app/output
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: ${CONNECTION_STRING}
    depends_on:
      - mysql
    networks:
      - my-network

  # phpmyadmin:
  #   env_file:
  #     - .env
  #   image: phpmyadmin/phpmyadmin:latest
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     PMA_HOST: mysql
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #   networks:
  #     - my-network

  # front-end:
  #   build: ./front-end
  #   container_name: front_end_c
  #   ports:
  #     - "3000:3000"
  #   stdin_open: true
  #   tty: true
  #   volumes:
  #     - ./front-end:/usr/src/app/front_end
  #     - /usr/src/app/front-end/node_modules