-- Create the db you need
CREATE DATABASE IF NOT EXISTS Hospital;

-- Use the db you created
USE Hospital;

CREATE TABLE IF NOT EXISTS `Doctors` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(255) NOT NULL,
  `LastName` VARCHAR(255) NOT NULL,
  `Age` INT(11) NOT NULL,
  `Salary` DOUBLE NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Addresses` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Country` VARCHAR(255) NOT NULL,
  `City` VARCHAR(255) NOT NULL,
  `PostalCode` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS `Rooms` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;


CREATE TABLE IF NOT EXISTS `Patients` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(255) NOT NULL,
  `LastName` VARCHAR(255) NOT NULL,
  `Age` INT(11) NOT NULL,
  `EntryDate` DATETIME NOT NULL,
  `ExitDate` DATETIME NOT NULL,
  `AddressId` INT(11) NOT NULL,
  `RoomId` INT(11) NOT NULL,
  `DoctorId` INT(11) NOT NULL,
  PRIMARY KEY (`id`),
  FOREIGN KEY (`AddressId`) REFERENCES `Addresses`(`id`),
  FOREIGN KEY (`RoomId`) REFERENCES `Rooms`(`id`),
  FOREIGN KEY (`DoctorId`) REFERENCES `Doctors`(`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;